---
title: "week12"
output: html_document
---

https://stats.idre.ucla.edu/r/dae/poisson-regression/
https://stats.stackexchange.com/questions/66586/is-there-a-test-to-determine-whether-glm-overdispersion-is-significant
https://stats.idre.ucla.edu/r/dae/negative-binomial-regression/
https://www.jamesuanhoro.com/post/2018/05/07/simulating-data-from-regression-models/
https://clanfear.github.io/Stata_R_Equivalency/docs/count_models.html
https://francish.netlify.app/post/poisson-and-negative-binomial-regression-using-r/
https://stats.stackexchange.com/questions/221648/negative-binomial-regression-in-r-allowing-for-correlation-between-dispersion

## Zero counts
https://fukamilab.github.io/BIO202/04-C-zero-data.html
https://stats.idre.ucla.edu/r/dae/zinb/
https://stats.idre.ucla.edu/r/dae/zip/

```{r}
library(AER)
library(here)
library(pscl)
library(MASS)
library(dplyr)
library(tidyr)
library(purrr)
library(haven)
library(forcats)
library(ggplot2)
library(sjlabelled)
```

```{r}
data <- haven::read_dta(here("class data.dta"))
```

```{r}
dataClean <-
    data %>%
    mutate(male = as.numeric(as.character(fct_recode(sjlabelled::as_factor(sex),
                                                    "0" = "2"))),
           f4hhdg = if_else(is.na(f4hhdg), 0, as.numeric(f4hhdg)),
           f4idrink = as.numeric(f4idrink),
           f4aempl = as.numeric(f4aempl)) %>%
    select(male, f4hhdg, f4aempl, f4idrink) %>%
    filter(across(everything(), ~!is.na(.x)))
```

Don't forget to exponentiate.

```{r}
poissonModel <- glm(f4idrink ~ ., family="poisson", data = dataClean)
summary(poissonModel)
```

Assessing model fit

```{r}
simulate <-
    simulate(poissonModel, 100) %>%
    pivot_longer(everything()) %>%
    count(value) %>%
    mutate(prcnt = n / sum(n),
           type = "sim") %>%
    rename(f4idrink = value)

real <-
    dataClean %>%
    count(f4idrink) %>%
    mutate(prcnt = n / sum(n),
           type = "real")

compare <- bind_rows(simulate, real)

compare %>%
    ggplot(aes(x = f4idrink, y = prcnt)) +
    geom_line(aes(color = type, group = type)) +
    geom_point(aes(color = type)) +
    theme_bw()
```

```{r}
negBin <- MASS::glm.nb(f4idrink ~ ., data = dataClean)
summary(negBin)
AER::dispersiontest(poissonModel)
pscl::odTest(negBin)

simulateNegBin <-
    simulate(negBin, 1) %>%
    pivot_longer(everything()) %>%
    count(value) %>%
    mutate(prcnt = n / sum(n),
           type = "simNegBin") %>%
    rename(f4idrink = value) %>%
    filter(f4idrink <= 30)

compareRealNegBin <- bind_rows(simulateNegBin, real)

compareRealNegBin %>%
    ggplot(aes(x = f4idrink, y = prcnt)) +
    geom_line(aes(color = type, group = type)) +
    geom_point(aes(color = type)) +
    theme_bw()
```

Can also do predictions.

```{r}
predictGender <- tibble(male = 0,
                        f4hhdg = mean(dataClean$f4hhdg),
                        f4aempl = mean(dataClean$f4aempl))

predictionsGender <- predict(negBin, newdata = predictGender, type = "response")

predictEmpl <- tibble(male = mean(dataClean$male),
                      f4hhdg = mean(dataClean$f4hhdg),
                      f4aempl = c(0, 1))

predictionsEmpl <- predict(negBin, newdata = predictEmpl, type = "response")
predictedProb <- pscl::predprob(negBin) %>% colMeans()


predictFemale <- tibble(male = 0,
                        f4hhdg = mean(dataClean$f4hhdg),
                        f4aempl = mean(dataClean$f4aempl))

predictMale <- tibble(male = 1,
                      f4hhdg = mean(dataClean$f4hhdg),
                      f4aempl = mean(dataClean$f4aempl))

predictedProbMale <- predprob(negBin, newdata = predictMale) %>% colMeans()
predictedProbFemale <- predprob(negBin, newdata = predictFemale) %>% colMeans()
```

## Zero Counts

```{r}
zinb <- pscl::zeroinfl(f4idrink ~ . | ., data = dataClean, dist = "negbin")
zip <- pscl::zeroinfl(f4idrink ~ . | ., data = dataClean)
summary(zinb)
BIC(zinb)
BIC(negBin)
BIC(zip)
```
